name: 每日微信消息推送

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装全部依赖包(清华源加速)
        run: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple requests ephem zhdate
      - name: 执行推送脚本
        env:
          GAODE_KEY: ${{ secrets.GAODE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: python main.py
