name: 每日微信推送

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - name: 执行推送
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          GAODE_KEY: ${{ secrets.GAODE_KEY }}
          USER: ${{ secrets.USER }}
          LOVE_DATE: ${{ secrets.LOVE_DATE }}
          BIRTHDAY1_NAME: ${{ secrets.BIRTHDAY1_NAME }}
          BIRTHDAY1_DATE: ${{ secrets.BIRTHDAY1_DATE }}
          BIRTHDAY2_NAME: ${{ secrets.BIRTHDAY2_NAME }}
          BIRTHDAY2_DATE: ${{ secrets.BIRTHDAY2_DATE }}
        run: python main.py
